version: '3.8'

services:
  # PostgreSQL Service
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=oauth_ab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Service
  redis-cache:
    image: redis:7-alpine
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass myredispassword
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: